apiVersion: v1
kind: Service
metadata:
  labels:
    app: mario-trivia
  name: mario-trivia
spec:
  ports:
  - name: "8081"
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mario-trivia
  type: NodePort
